from .shoppinglist import ShoppingList


def shoplist(request):
    """
    Generates a list of items from a ShoppingList instance associated with the request.

    :param request: HttpRequest object generated by Django.
    :type request: HttpRequest
    :return: Dictionary containing a list of item slugs under the key 'shoplist'.
    :rtype: dict
    """
    shoppinglist = ShoppingList(request)
    return {
        "shoplist": shoppinglist.get_objects().values_list("slug", flat=True)
    }
