from recipes.models import Recipe
from recipes.utils import get_ingredients


SHOPPINGLIST_SESSION_ID = "shoppinglist"


class ShoppingList:
    def __init__(self, request):
        """
        Initializes a ShoppingList object associated with the provided request.

        :param request: HttpRequest object generated by Django.
        :type request: HttpRequest
        """
        self.session = request.session
        shoppinglist = self.session.get(SHOPPINGLIST_SESSION_ID)
        if shoppinglist is None:
            shoppinglist = self.session[SHOPPINGLIST_SESSION_ID] = []
        self.shoppinglist = shoppinglist

    def add(self, recipe_id):
        """
        Adds a recipe to the shopping list.

        :param recipe_id: Identifier of the recipe to add to the shopping list.
        :type recipe_id: int
        """
        if recipe_id not in self.shoppinglist:
            self.shoppinglist.append(recipe_id)
        self.save()

    def save(self):
        """
        Saves the shopping list to the session.
        """
        self.session.modified = True

    def remove(self, recipe_id):
        """
        Removes a recipe from the shopping list.

        :param recipe_id: Identifier of the recipe to remove from the shopping list.
        :type recipe_id: int
        """
        if recipe_id in self.shoppinglist:
            self.shoppinglist.remove(recipe_id)
            self.save()

    def __len__(self):
        """
        Returns the number of recipes in the shopping list.

        :return: Number of recipes in the shopping list.
        :rtype: int
        """
        return len(self.shoppinglist)

    def __iter__(self):
        """
        Iterates through the recipes in the shopping list.

        :return: Iterator over Recipe objects.
        :rtype: Iterator[Recipe]
        """
        recipes_id = self.shoppinglist
        recipes = Recipe.objects.filter(id__in=recipes_id)
        for recipe in recipes:
            yield recipe

    def get_objects(self):
        """
        Retrieves Recipe objects from the shopping list.

        :return: QuerySet of Recipe objects.
        :rtype: QuerySet[Recipe]
        """
        return Recipe.objects.filter(id__in=self.shoppinglist)

    def clear(self):
        """
        Clears the shopping list by removing all items.
        """
        del self.session[SHOPPINGLIST_SESSION_ID]
        self.save()

    def get_ingridients_for_pdf(self):
        """
        Gathers ingredients from recipes in the shopping list for generating a PDF.

        :return: List of ingredients formatted for PDF generation.
        :rtype: List[List[str, float, str, List[str]]]
        """
        recipes_id = self.shoppinglist
        recipes = Recipe.objects.filter(id__in=recipes_id)
        ingridients_for_pdf = {}
        for recipe in recipes:
            recipe_ingridients = get_ingredients(recipe)
            for ingridient in recipe_ingridients:
                title, value, dimention = ingridient

                ingridients_for_pdf[title] = ingridients_for_pdf.get(
                    title, [0, dimention, []]
                )
                ingridients_for_pdf[title][0] += value.value
                ingridients_for_pdf[title][2].append(recipe.name)

        ingridients_for_pdf = [
            [title, value[0], value[1], value[2]]
            for title, value in ingridients_for_pdf.items()
        ]

        return ingridients_for_pdf
