from django.shortcuts import render


def page_not_found(request, exception):
    """
    Renders a custom 404 error page when a requested page is not found.

    :param request: HttpRequest object generated by Django.
    :type request: HttpRequest
    :param exception: Exception raised when the requested page is not found.
    :type exception: Exception
    :return: HttpResponse rendering the custom 404 error page.
    :rtype: HttpResponse
    """
    return render(request, "misc/404.html", {"path": request.path}, status=404)


def server_error(request):
    """
    Renders a custom 500 server error page.

    :param request: HttpRequest object generated by Django.
    :type request: HttpRequest
    :return: HttpResponse rendering the custom 500 error page.
    :rtype: HttpResponse
    """
    return render(request, "misc/500.html", status=500)
